//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approver
    {
        public System.Guid Id { get; set; }
        public string JobCode { get; set; }
        public int AreaLeve { get; set; }
        public string Discrible { get; set; }
        public int OrderApps { get; set; }
        public Nullable<System.Guid> ProcessItemId { get; set; }
        public string ExecuteMethod { get; set; }
    
        public virtual ProcessItem ProcessItem { get; set; }
    }
}
