//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public System.Guid Id { get; set; }
        public string StaffName { get; set; }
        public bool Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<bool> MaritalStatus { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<int> HighestEducation { get; set; }
        public string Major { get; set; }
        public string ForeginLanguageAptitude { get; set; }
        public string IDNumber { get; set; }
        public string NativePlace { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public Nullable<bool> HaseMedicalHistory { get; set; }
        public string MedicalHistoryComment { get; set; }
        public string HobbiesAndSpeciality { get; set; }
        public Nullable<System.DateTime> EducationalExperience1StartDate { get; set; }
        public Nullable<System.DateTime> EducationalExperience1EndDate { get; set; }
        public string EducationalExperience1SchoolName { get; set; }
        public string EducationalExperience1Major { get; set; }
        public string EducationalExperience1Certificate { get; set; }
        public Nullable<System.DateTime> EducationalExperience2StartDate { get; set; }
        public Nullable<System.DateTime> EducationalExperience2EndDate { get; set; }
        public string EducationalExperience2SchoolName { get; set; }
        public string EducationalExperience2Major { get; set; }
        public string EducationalExperience2Certificate { get; set; }
        public Nullable<System.DateTime> EducationalExperience3StartDate { get; set; }
        public Nullable<System.DateTime> EducationalExperience3EndDate { get; set; }
        public string EducationalExperience3SchoolName { get; set; }
        public string EducationalExperience3Major { get; set; }
        public string EducationalExperience3Certificate { get; set; }
        public Nullable<System.DateTime> EducationalExperience4StartDate { get; set; }
        public Nullable<System.DateTime> EducationalExperience4EndDate { get; set; }
        public string EducationalExperience4SchoolName { get; set; }
        public string EducationalExperience4Major { get; set; }
        public string EducationalExperience4Certificate { get; set; }
        public string FamilyStatus1Name { get; set; }
        public string FamilyStatus1Appellation { get; set; }
        public string FamilyStatus1Company { get; set; }
        public string FamilyStatus1Tel { get; set; }
        public string FamilyStatus2Name { get; set; }
        public string FamilyStatus2Appellation { get; set; }
        public string FamilyStatus2Company { get; set; }
        public string FamilyStatus2Tel { get; set; }
        public string EmergencyContactName { get; set; }
        public string EmergencyContactTel { get; set; }
        public string EmergencyContactEelationShipWithMe { get; set; }
        public string WorkExperience1CompanyName { get; set; }
        public string WorkExperience1Job { get; set; }
        public Nullable<System.DateTime> WorkExperience1StartDate { get; set; }
        public Nullable<System.DateTime> WorkExperience1EndDate { get; set; }
        public string WorkExperience1Pay { get; set; }
        public string WorkExperience1LeavingReasons { get; set; }
        public string WorkExperience2CompanyName { get; set; }
        public string WorkExperience2Job { get; set; }
        public Nullable<System.DateTime> WorkExperience2StartDate { get; set; }
        public Nullable<System.DateTime> WorkExperience2EndDate { get; set; }
        public string WorkExperience2Pay { get; set; }
        public string WorkExperience2LeavingReasons { get; set; }
        public string WorkExperience3CompanyName { get; set; }
        public string WorkExperience3Job { get; set; }
        public Nullable<System.DateTime> WorkExperience3StartDate { get; set; }
        public Nullable<System.DateTime> WorkExperience3EndDate { get; set; }
        public string WorkExperience3Pay { get; set; }
        public string WorkExperience3LeavingReasons { get; set; }
        public string WorkExperience4CompanyName { get; set; }
        public string WorkExperience4Job { get; set; }
        public Nullable<System.DateTime> WorkExperience4StartDate { get; set; }
        public Nullable<System.DateTime> WorkExperience4EndDate { get; set; }
        public string WorkExperience4Pay { get; set; }
        public string WorkExperience4LeavingReasons { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> Organization_Id { get; set; }
        public string SupervisorComments { get; set; }
        public string ProbationarySalary { get; set; }
        public string CorrectSalary { get; set; }
        public string WorkNumber { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string BirthCertificatePhoto { get; set; }
        public string RegistrationPhoto { get; set; }
        public string BankCardNumber { get; set; }
        public Nullable<System.Guid> CreateStaffeId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string No { get; set; }
        public string StaffNo { get; set; }
        public bool IsDel { get; set; }
    }
}
