//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveOffice
    {
        public System.Guid Id { get; set; }
        public string No { get; set; }
        public string StaffName { get; set; }
        public System.Guid JobId { get; set; }
        public string LeaveType { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string Reason { get; set; }
        public string ExplanationHandover { get; set; }
        public Nullable<System.Guid> HandoverSatffId { get; set; }
        public Nullable<System.Guid> ApplyPersonId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<bool> IsDel { get; set; }
    }
}
