//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OilMaterialOrderDetail
    {
        public System.Guid Id { get; set; }
        public System.Guid OrderId { get; set; }
        public string OilSpec { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Surplus { get; set; }
        public Nullable<decimal> DayAvg { get; set; }
        public Nullable<decimal> NeedAmount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<bool> IsDel { get; set; }
    
        public virtual OilMaterialOrder OilMaterialOrder { get; set; }
    }
}
