//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oss.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public System.Guid Id { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string NativePlace { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public Nullable<System.Guid> OrgID { get; set; }
        public Nullable<bool> IsHSEGroup { get; set; }
    }
}
